---
name: Run tests

on: [push, pull_request, workflow_dispatch]

env:
  PIP_ROOT_USER_ACTION: ignore

jobs:
  test_linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt;
          fi
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install openvpn
      - name: Run tests
        run: |
          pytest test_openvpnclient.py -s -v
